server:
  port: 9031
spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: comment:com.dheeraj.commentWriteService.model.Comment
      
    
